### ISSUE TITLE
Lodash vulnerability

### ISSUE THREAD

**Issue by cortopy** [Sai1919/xml-streamer#16]
Please do note that there is security advisory for the version of lodash this package uses: https://www.npmjs.com/advisories/1065

**Comment by Sai1919** [comment]
@cortopy Thanks for reporting this. I have plans to fix this over the coming weekend or contributions are always most welcome.

**Comment by Sai1919** [comment]
Fixed as part of this PR: https://github.com/Sai1919/xml-streamer/pull/15
