### ISSUE TITLE
pipe will not close input if root node is incorrect

### ISSUE THREAD

**Issue by pludov** [Sai1919/xml-streamer#5]
When the root node is not matched, XmlStreamer will prematurely close. If using pipe, this leaves the input stream partially consumed and unclosed, requiring extra code for cleanup. 

```
var file = fs.createInputStream('file_without_a.xml');
var streamer = new XmlStreamer({
    resourcePath: '/a'
});
file.stream(streamer);
// extra code required to close file in case the root tag did not match

```

**Comment by Sai1919** [comment]
@pludov Hey thanks for reporting issues and for contribution. I will try to go through these in the weekend :)

**Comment by Sai1919** [comment]
Fixed with this PR: https://github.com/Sai1919/xml-streamer/pull/8
